### PR TITLE
add jokes

### PR DESCRIPTION
**Pull request by Mustafiz04**
Earlier there was a conflicting files

### CODE REVIEW

**Comment by Mustafiz04** [comment]
So how can I change that by requesting another PR with correction?

**Comment by Mustafiz04** [comment]
Actually I'm not completely comfortable with GitHub. Still I am learning.
I correct that but I'm not sure it is working or not.

**Comment by shrutikapoor08** [comment]
Good job!

**Comment by Mustafiz04** [comment]
Thank You, Maam

**Pull request merged**
