### PR TITLE
Create sarcasticdev

### PR DESCRIPTION
**Pull request by hemant2705**
be like dev!!

### CODE REVIEW

**Comment by debone** [comment]
Thank you for your contribution! I didn't quite got your joke. Can you provide an explanation or improve the wording?

**Comment by hemant2705** [comment]
WhatsApp Image 2020-10-04 at 02 31 18
hope u get my joke now . just a beginner ,trying to learn to use github.

**Comment by debone** [comment]
Sorry but I don't see it :/ I will leave it open for another maintainer to check it

**Comment by shrutikapoor08** [comment]
Thank you for submitting the joke! I added the label and you should credit soon

**Pull request closed without merging**
