### PR TITLE
Adding joke

### PR DESCRIPTION
**Pull request by Dkaban**

### CODE REVIEW

**Review by shrutikapoor08 — CHANGES_REQUESTED** [review]
Looks like this could use some code formatting.

**Review by Dkaban — COMMENTED** [review]
changed *** to * * *

**Review by shrutikapoor08 — APPROVED** [review]

**Comment by shrutikapoor08** [comment]
can you resolve conflicts? gtg afterwards

**Comment by Dkaban** [comment]
Thanks shruti, this is my first PR so I appreciate your patience!

**Pull request merged**
