### PR TITLE
just a joke with batman

### PR DESCRIPTION
**Pull request by hacknorris-notyetbanned**

### CODE REVIEW

**Comment by hacknorris-notyetbanned** [comment]
! it was made by me, i didnt copied! ( i just thought and shared :D )

**Review by shrutikapoor08 — CHANGES_REQUESTED** [review]
Thank you for creating the joke! I think it could use a rewording.

**Comment by hacknorris-notyetbanned** [comment]
thx for answer ^_^

**Comment by hacknorris-notyetbanned** [comment]
okay, 1 word changed!

**Pull request closed without merging**
