### PR TITLE
Added Content to README.md

### PR DESCRIPTION
**Pull request by girotramanav**

### CODE REVIEW

**Comment by debone** [comment]
Thank you for your contribution! I didn't quite got your joke. Can you provide an explanation or improve the wording?

**Comment by girotramanav** [comment]
Well it describes the event which occurs sometimes while coding we try to do the same thing with our code we have done already but our code works differently. If still there is some issue with this I can make it a pictorial one or try another joke. Thanks for the review.😀

**Comment by debone** [comment]
Ok! I got it :) So please cleanup the wording, like the whole upper case sentence.

**Comment by girotramanav** [comment]
It's Done!

**Comment by debone** [comment]
Thanks!

**Pull request merged**
