### PR TITLE
Added More Memes And Jokes. Update README.md

### PR DESCRIPTION
**Pull request by uditpatel2526**
I have added more jokes and more memes to the images folder and updated the README.md file

### CODE REVIEW

**Comment by uditpatel2526** [comment]
Please Don't Forget to ADD the hacktoberfest-accepted label to this pull request.

**Review by shrutikapoor08 — CHANGES_REQUESTED** [review]
Hey, thanks for submitting the PR. The image content should go in the appropriate image section (bottom). The JFIF files are not rendering in preview. Can you convert them to jpeg?

**Comment by uditpatel2526** [comment]
yeah I'll update the PR. Thanks for correcting me.

**Comment by uditpatel2526** [comment]
@shrutikapoor08 Can you review the changes please?

**Comment by uditpatel2526** [comment]
Hey @shrutikapoor08  these changes are long been waiting to be merged. Can you please review them?

**Comment by uditpatel2526** [comment]
Thank You @shrutikapoor08 .

**Pull request closed without merging**
