### PR TITLE
Adding joke to the amazing list of fun for programmers

### PR DESCRIPTION
**Pull request by Harshi7016**

### CODE REVIEW

**Comment by Harshi7016** [comment]
@shrutikapoor08 This is so cool, Whenever I feel I need to take a timeout, I visit your list of dev jokes, laugh for a while... Get charged to work again :D

**Review by shrutikapoor08 — APPROVED** [review]
LOL thank you for this very relevant and accurate devjoke lol

**Comment by shrutikapoor08** [comment]
@Harshi7016 Thanks Harshith! I am happy to know that :D 
Seems like there are some conflicts due to recent merges. Could you resolve them please?

**Comment by Harshi7016** [comment]
@shrutikapoor08 , I hope this works :D

**Pull request merged**
