### PR TITLE
Dev Meme

### PR DESCRIPTION
**Pull request by itsnotsagar**

### CODE REVIEW

**Comment by itsnotsagar** [comment]
@shrutikapoor08 pls have a look!

**Review by shrutikapoor08 — CHANGES_REQUESTED** [review]
oh no! no shaming programmers. perhaps reword?

**Comment by itsnotsagar** [comment]
@shrutikapoor08 how bout now?

**Comment by shrutikapoor08** [comment]
this is great :D Just needs reference to the image in README

**Pull request closed without merging**
