### PR TITLE
Json parser

### PR DESCRIPTION
**Pull request by iam-agf**
The first commit just changes the emojis into :emojis: to help the parser not crash, but they're still there and when the text is run again as a markdown, they return.

The second and third commits are the final parser and the result. Since the markdown can be understood as an html too, the final README.md file splits the file finding the string `<hr />` . Then the rest of the chunks of text are added to the list of jokes in the json. Finally it is saved into the file `jokes.json`.

The code can be improved by changing some lines, but for now I need to know if this method is adequate for what the owners of the repository need or if I must approach the task in other way.

### CODE REVIEW

**Review by shrutikapoor08 — CHANGES_REQUESTED** [review]
First of all, thanks for doing this! This was needed for a long time!
Question - why does the parser output has html in json? It is preferred to have pure strings so that it can  be used in other applications. 

Second - I wanted to say if you are interested in hacktoberfest, you can submit this pull request on October 1 so it can count towards your open source contribution :)

**Comment by MadhavBahlMD** [comment]
Also, @iam-agf please add the parsed JSON result as well,

Let's say in `output` directory, or `parserOutput`

**Comment by iam-agf** [comment]
@shrutikapoor08 Yes, I'm interested in the Hacktoberfest, but the main purpose is to help others, so a small PR before October can't hurt :)

The Html format is because Python didn't read the markdown as a raw file. It read the processed content. I will look for a solution for this and add it. Can the string contain special characters like `\n` or others like this?

Since you don't have hurry in finishing this, I will try to complete the task and add it to count in Hacktoberfest. Also I will add another branch in order to avoid conflicts with the master, because I forgot to add a small comment in the `README.md` to help the parser avoid failing for future contributions.

@MadhavBahlMD Ok, I will add this in the next PR. It will be called `parserOutput`, as you recommended.

**Comment by MadhavBahlMD** [comment]
Thanks for the contribution @iam-agf

**Comment by iam-agf** [comment]
Just to confirm. The way I achieved to let the strings of the jokes is like these two examples:

`
\"Knock, knock.\"\n\n\"Who's there?\"\n\nvery... long... pause...\n\n\"Java.\"
`

`A guy ordered a pizza with cheese, olives, onion and red pepper. On getting it, the guy shouted - It is not baked. \n\nDelivery guy - You only get what you ask for.`

Is this way good enough or would you prefer me to delete the `\n` chars?

**Comment by shrutikapoor08** [comment]
`\n` is okay :) @iam-agf

**Comment by shrutikapoor08** [comment]
Thank you for your contribution. Going to close this PR since a similar PR has been merged.

**Pull request closed without merging**
