### PR TITLE
Dev joke

### PR DESCRIPTION
**Pull request by him2016**

### CODE REVIEW

**Comment by debone** [comment]
Thank you for your contribution! We welcome jokes but your second joke is a duplicated :) Please make sure the joke is not in the file already

Also, the first one requires some work as the joke is not quite there.

**Comment by him2016** [comment]
Have updated it. Pls check.

**Comment by debone** [comment]
Thanks. I see think now these are fine but the second one is missing a punchline. Can you improve the wording or remove it?

**Comment by him2016** [comment]
Have removed the second one. Pls check.

**Comment by debone** [comment]
Thank you!

**Pull request merged**
