### PR TITLE
Update Dev Joke

### PR DESCRIPTION
**Pull request by stevensiahaan**

### CODE REVIEW

**Comment by shrutikapoor08** [comment]
what is the joke here?

**Comment by stevensiahaan** [comment]
> what is the joke here?

it's not a joke if I have to explain it :)

**Comment by pksjce** [comment]
Well.. I kinda get it I think. Its a reference to how none of the declarations including the comment give out no context on what the array actually does. 
Its missing a good punchline I think.

**Comment by debone** [comment]
It could be

```
intern: $array = array();
PR: please comment your code
intern: $array = array(); //array
PR: 
intern: $array = array(); // Initializing array
```

**Pull request closed without merging**
